services:
  fakevine:
    image: ghcr.io/falo2k/fakevine:latest
    ports:
      - "8463:8463"
    volumes:
      - fakevine-data:/data
    environment:
      - FAKEVINE_LOG_FILE_ENABLE=true
      - FAKEVINE_CACHE_CV_API_KEY=replaceme
    restart: unless-stopped

volumes:
  fakevine-data:
